### ISSUE TITLE
Wiki link with title is not properly escaped in table query

### ISSUE THREAD

**Issue by GordianDziwis** [dsebastien/obsidian-dataview-serializer#35]
The link to the "rdf-types" note is missing the `\` to escape the `|`.

### Frontmatter

```yaml
aliases:
  - rdf-types
dependency:
  repository: https://github.com/timothee-haudebourg/rdf-types
  category: "[[20250314160714|RDF type library]]"
tags: []
```

### Query
```md
<!-- QueryToSerialize: table  dependency.category where dependency -->
<!-- SerializedQuery: table  dependency.category where dependency -->

| File                                  | dependency.category                     |
| ------------------------------------- | --------------------------------------- |
| [[20250314150534|rdf-types]] | [[20250314160714\|RDF type library]] |
<!-- SerializedQuery END -->
```
