### ISSUE TITLE
Recommended CSS snippet: Hide HTML comments on non-active lines

### ISSUE THREAD

**Issue by vergenzt** [dsebastien/obsidian-dataview-serializer#37]
Hi! I just came up with this snippet for my own use and figured I'd share it:

```css
/* filename: .obsidian/snippets/hide-non-active-comments.css */
/* Hide HTML comments in non-active lines (displays as `<-- …`) */
.cm-line:not(.cm-active) .cm-comment {
  display: block;
  max-width: 5ch;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  font-style: italic;
}
```

### Without the snippet:
![Image](https://github.com/user-attachments/assets/fb89babb-3d16-4c06-bc8d-6f9978b54f8b)

### With the snippet, cursor not on any comment line:
![Image](https://github.com/user-attachments/assets/d8cc337b-4be9-476c-bb9c-59bfc1134284)

### With the snippet, cursor on first comment line:
![Image](https://github.com/user-attachments/assets/0fdd83e4-4c3d-4d41-89bc-bf645b0bad10)
